version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/dog
    ports:
      - "3333:3333"
    command: ["yarn", "dev"]
